# Generated by Django 5.0.6 on 2025-04-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_promocode_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
