# Generated by Django 5.0.6 on 2025-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_foodcategory_fooditem_order_orderitem_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='category_type',
            field=models.CharField(blank=True, choices=[('origin', 'Origin'), ('cuisine', 'Cuisine'), ('preparation', 'Preparation'), ('meal_type', 'Meal Type'), ('Groceries', 'Groceries Type')], max_length=50, null=True),
        ),
    ]
