# Generated by Django 5.0.6 on 2025-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_foodcategory_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Cash on Delivery'), ('Card', 'Card'), ('UPI', 'UPI')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Food Options', 'Food Options'), ('Shop Groceries on Instamart', 'Shop Groceries on Instamart'), ('Restaurants', 'Restaurants'), ('Special', 'Special'), ('Festival', 'Festival')], max_length=50, null=True),
        ),
    ]
