# Generated by Django 5.0.6 on 2025-04-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_order_delivery_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('Cooked_And_Delivered', 'Cooked_And_Delivered')], default='pending', max_length=20),
        ),
    ]
